### ISSUE TITLE
- AmirAli ¯̶̄Mïłtøη

### ISSUE THREAD

**Issue by AmirAli-REback** [AmirAli-REback/NUCK-BOT#1]
**LINKS:**
[DISCORD](https://discord.gg/ecpCnZP9aj)

=============================================
**TASK list:**
- [x] کیک کردن تمام ممبر ها. 
- [x] - [x] دیلیت کردن چنل ها.  
- [x] - [x] دیلیت کردن رول ها
